package clusterspec

import (
	"strings"
	"testing"

	"sigs.k8s.io/yaml"
)

func intp(i int) *int { return &i }

func TestRender_MinimalDefaults(t *testing.T) {
	in := Input{Name: "dev-eks", Account: "111111111111", Region: "us-west-2", Team: "platform"}
	out, err := in.Render()
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	// Parse it back to assert structure (and that it is valid YAML).
	var cr clusterCR
	if err := yaml.Unmarshal([]byte(out), &cr); err != nil {
		t.Fatalf("rendered output is not valid YAML: %v\n%s", err, out)
	}
	if cr.APIVersion != apiVersion || cr.Kind != kind {
		t.Errorf("apiVersion/kind = %q/%q", cr.APIVersion, cr.Kind)
	}
	if cr.Metadata.Name != "dev-eks" || cr.Metadata.Namespace != "platform" {
		t.Errorf("metadata = %+v, want name=dev-eks namespace=platform", cr.Metadata)
	}
	if cr.Spec.Environment != "dev" || cr.Spec.ClusterVersion != "1.36" {
		t.Errorf("defaults not applied: env=%q version=%q", cr.Spec.Environment, cr.Spec.ClusterVersion)
	}
	if cr.Spec.Account != "111111111111" || cr.Spec.Region != "us-west-2" || cr.Spec.Team != "platform" {
		t.Errorf("required spec fields wrong: %+v", cr.Spec)
	}
	// Optional blocks omitted when unset.
	if cr.Spec.SystemNodes != nil || cr.Spec.Network != nil {
		t.Errorf("optional blocks should be omitted when unset")
	}
	if !strings.HasPrefix(out, "# Generated by portal") {
		t.Errorf("missing provenance header")
	}
}

func TestRender_FullSpec(t *testing.T) {
	yes := true
	in := Input{
		Name: "prod-eks", Account: "222222222222", Region: "us-east-1", Team: "platform",
		Environment: "production", ClusterVersion: "1.34",
		SystemNodes:               &SystemNodes{InstanceTypes: []string{"m7g.2xlarge"}, MinSize: intp(3), MaxSize: intp(9), DesiredSize: intp(3), DiskSize: intp(200)},
		Network:                   &Network{VpcCidr: "10.4.0.0/16", MaxAzs: intp(3), NatGateways: intp(3)},
		EndpointPublicAccess:      &yes,
		EndpointPublicAccessCidrs: []string{"203.0.113.0/24"},
		VendRoleArn:               "arn:aws:iam::222222222222:role/production-eks-fleet-vend",
	}
	out, err := in.Render()
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	var cr clusterCR
	if err := yaml.Unmarshal([]byte(out), &cr); err != nil {
		t.Fatalf("invalid YAML: %v", err)
	}
	if cr.Spec.SystemNodes == nil || len(cr.Spec.SystemNodes.InstanceTypes) != 1 || *cr.Spec.SystemNodes.MaxSize != 9 {
		t.Errorf("systemNodes wrong: %+v", cr.Spec.SystemNodes)
	}
	if cr.Spec.Network == nil || cr.Spec.Network.VpcCidr != "10.4.0.0/16" || *cr.Spec.Network.NatGateways != 3 {
		t.Errorf("network wrong: %+v", cr.Spec.Network)
	}
	if cr.Spec.EndpointPublicAccess == nil || !*cr.Spec.EndpointPublicAccess {
		t.Errorf("endpointPublicAccess not rendered")
	}
	if cr.Spec.VendRoleArn == "" || !strings.Contains(out, "production-eks-fleet-vend") {
		t.Errorf("vendRoleArn not rendered")
	}
	// camelCase field names in the YAML (not snake_case).
	for _, want := range []string{"clusterVersion:", "systemNodes:", "instanceTypes:", "vpcCidr:", "natGateways:", "endpointPublicAccess:"} {
		if !strings.Contains(out, want) {
			t.Errorf("rendered YAML missing camelCase field %q:\n%s", want, out)
		}
	}
}

func TestWithCrossAccountBootstrap(t *testing.T) {
	const hub = "arn:aws:iam::111111111111:role/eks-fleet-crossplane"
	const vend = "arn:aws:iam::222222222222:role/production-eks-fleet-vend"
	cases := []struct {
		name     string
		in       Input
		hubRole  string
		wantBoot string
	}{
		{"cross-account stamps the hub role", Input{VendRoleArn: vend}, hub, hub},
		{"same-account leaves it empty", Input{VendRoleArn: ""}, hub, ""},
		{"explicit override is preserved", Input{VendRoleArn: vend, BootstrapAccessRoleArn: "arn:aws:iam::1:role/custom"}, hub, "arn:aws:iam::1:role/custom"},
		{"empty hub role is a no-op", Input{VendRoleArn: vend}, "", ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := tc.in.WithCrossAccountBootstrap(tc.hubRole).BootstrapAccessRoleArn; got != tc.wantBoot {
				t.Errorf("BootstrapAccessRoleArn = %q, want %q", got, tc.wantBoot)
			}
		})
	}
}

func TestRender_BootstrapAccessRoleArn(t *testing.T) {
	in := Input{
		Name: "prod-eks", Account: "222222222222", Region: "us-west-2", Team: "platform",
		VendRoleArn: "arn:aws:iam::222222222222:role/production-eks-fleet-vend",
	}.WithCrossAccountBootstrap("arn:aws:iam::111111111111:role/eks-fleet-crossplane")
	out, err := in.Render()
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	var cr clusterCR
	if err := yaml.Unmarshal([]byte(out), &cr); err != nil {
		t.Fatalf("invalid YAML: %v", err)
	}
	if cr.Spec.BootstrapAccessRoleArn != "arn:aws:iam::111111111111:role/eks-fleet-crossplane" {
		t.Errorf("bootstrapAccessRoleArn not rendered: %q", cr.Spec.BootstrapAccessRoleArn)
	}
	if !strings.Contains(out, "bootstrapAccessRoleArn:") {
		t.Errorf("rendered YAML missing camelCase bootstrapAccessRoleArn:\n%s", out)
	}
}

func TestValidate_Errors(t *testing.T) {
	base := Input{Name: "ok", Account: "111111111111", Region: "us-west-2", Team: "platform"}
	cases := map[string]func(*Input){
		"bad name":   func(i *Input) { i.Name = "Bad_Name" },
		"short acct": func(i *Input) { i.Account = "123" },
		"non-digit":  func(i *Input) { i.Account = "11111111111x" },
		"bad region": func(i *Input) { i.Region = "uswest2" },
		"bad team":   func(i *Input) { i.Team = "Platform/x" },
		"bad env":    func(i *Input) { i.Environment = "qa" },
	}
	for name, mut := range cases {
		t.Run(name, func(t *testing.T) {
			in := base
			mut(&in)
			if err := in.Validate(); err == nil {
				t.Errorf("expected validation error for %s", name)
			}
			if _, err := in.Render(); err == nil {
				t.Errorf("Render should reject %s", name)
			}
		})
	}
}

func TestEffectiveEnvironment(t *testing.T) {
	if (Input{}).EffectiveEnvironment() != "dev" {
		t.Error("empty env should default to dev")
	}
	if (Input{Environment: "staging"}).EffectiveEnvironment() != "staging" {
		t.Error("set env should pass through")
	}
}
