// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: clusters.sql

package repository

import (
	"context"
	"time"
)

const clusterColumns = `id, org_id, account_id, name, description, environment, api_endpoint, ca_bundle_encrypted, sa_token_encrypted, region, connection_status, last_connected_at, connection_error, node_count, k8s_version, created_by, created_at, updated_at`

func scanCluster(row interface{ Scan(...interface{}) error }) (Cluster, error) {
	var c Cluster
	err := row.Scan(&c.ID, &c.OrgID, &c.AccountID, &c.Name, &c.Description, &c.Environment, &c.APIEndpoint, &c.CABundleEncrypted, &c.SATokenEncrypted, &c.Region, &c.ConnectionStatus, &c.LastConnectedAt, &c.ConnectionError, &c.NodeCount, &c.K8sVersion, &c.CreatedBy, &c.CreatedAt, &c.UpdatedAt)
	return c, err
}

type GetClusterParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetCluster(ctx context.Context, arg GetClusterParams) (Cluster, error) {
	row := q.db.QueryRow(ctx,
		`SELECT `+clusterColumns+` FROM clusters WHERE id = $1 AND org_id = $2`,
		arg.ID, arg.OrgID,
	)
	return scanCluster(row)
}

type ListClustersParams struct {
	OrgID     string `json:"org_id"`
	AccountID string `json:"account_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListClusters(ctx context.Context, arg ListClustersParams) ([]Cluster, error) {
	rows, err := q.db.Query(ctx,
		`SELECT `+clusterColumns+` FROM clusters
		WHERE org_id = $1
		  AND ($2::TEXT = '' OR account_id = $2)
		ORDER BY created_at DESC LIMIT $3 OFFSET $4`,
		arg.OrgID, arg.AccountID, arg.Limit, arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var clusters []Cluster
	for rows.Next() {
		c, err := scanCluster(rows)
		if err != nil {
			return nil, err
		}
		clusters = append(clusters, c)
	}
	if clusters == nil {
		clusters = []Cluster{}
	}
	return clusters, rows.Err()
}

type CountClustersParams struct {
	OrgID     string `json:"org_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) CountClusters(ctx context.Context, arg CountClustersParams) (int64, error) {
	row := q.db.QueryRow(ctx,
		`SELECT COUNT(*) FROM clusters
		WHERE org_id = $1
		  AND ($2::TEXT = '' OR account_id = $2)`,
		arg.OrgID, arg.AccountID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

type CreateClusterParams struct {
	ID                string `json:"id"`
	OrgID             string `json:"org_id"`
	AccountID         string `json:"account_id"`
	Name              string `json:"name"`
	Description       string `json:"description"`
	Environment       string `json:"environment"`
	APIEndpoint       string `json:"api_endpoint"`
	CABundleEncrypted string `json:"ca_bundle_encrypted"`
	SATokenEncrypted  string `json:"sa_token_encrypted"`
	Region            string `json:"region"`
	CreatedBy         string `json:"created_by"`
}

func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error) {
	row := q.db.QueryRow(ctx,
		`INSERT INTO clusters (id, org_id, account_id, name, description, environment, api_endpoint, ca_bundle_encrypted, sa_token_encrypted, region, created_by)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
		RETURNING `+clusterColumns,
		arg.ID, arg.OrgID, arg.AccountID, arg.Name, arg.Description, arg.Environment, arg.APIEndpoint, arg.CABundleEncrypted, arg.SATokenEncrypted, arg.Region, arg.CreatedBy,
	)
	return scanCluster(row)
}

type UpdateClusterParams struct {
	ID                string `json:"id"`
	OrgID             string `json:"org_id"`
	Name              string `json:"name"`
	Description       string `json:"description"`
	Environment       string `json:"environment"`
	APIEndpoint       string `json:"api_endpoint"`
	CABundleEncrypted string `json:"ca_bundle_encrypted"`
	SATokenEncrypted  string `json:"sa_token_encrypted"`
	Region            string `json:"region"`
}

func (q *Queries) UpdateCluster(ctx context.Context, arg UpdateClusterParams) (Cluster, error) {
	row := q.db.QueryRow(ctx,
		`UPDATE clusters
		SET name = COALESCE(NULLIF($3, ''), name),
			description = COALESCE(NULLIF($4, ''), description),
			environment = COALESCE(NULLIF($5, ''), environment),
			api_endpoint = COALESCE(NULLIF($6, ''), api_endpoint),
			ca_bundle_encrypted = COALESCE(NULLIF($7, ''), ca_bundle_encrypted),
			sa_token_encrypted = COALESCE(NULLIF($8, ''), sa_token_encrypted),
			region = COALESCE(NULLIF($9, ''), region),
			updated_at = NOW()
		WHERE id = $1 AND org_id = $2
		RETURNING `+clusterColumns,
		arg.ID, arg.OrgID, arg.Name, arg.Description, arg.Environment, arg.APIEndpoint, arg.CABundleEncrypted, arg.SATokenEncrypted, arg.Region,
	)
	return scanCluster(row)
}

type DeleteClusterParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeleteCluster(ctx context.Context, arg DeleteClusterParams) error {
	_, err := q.db.Exec(ctx,
		`DELETE FROM clusters WHERE id = $1 AND org_id = $2`,
		arg.ID, arg.OrgID,
	)
	return err
}

// SetClusterConnectionStatus writes the async connection-test job's results.
// On success: status='connected', last_connected_at=now(), node_count + k8s_version
// populated, error cleared. On failure: status='failed', error populated,
// other fields untouched so the last good values stay visible.
type SetClusterConnectionStatusParams struct {
	ID         string    `json:"id"`
	OrgID      string    `json:"org_id"`
	Status     string    `json:"status"`
	Error      string    `json:"error"`
	NodeCount  int32     `json:"node_count"`
	K8sVersion string    `json:"k8s_version"`
	At         time.Time `json:"at"`
}

func (q *Queries) SetClusterConnectionStatus(ctx context.Context, arg SetClusterConnectionStatusParams) error {
	if arg.Status == "connected" {
		_, err := q.db.Exec(ctx,
			`UPDATE clusters
			SET connection_status = $3::cluster_connection_status,
				last_connected_at = $4,
				connection_error = '',
				node_count = $5,
				k8s_version = $6,
				updated_at = NOW()
			WHERE id = $1 AND org_id = $2`,
			arg.ID, arg.OrgID, arg.Status, arg.At, arg.NodeCount, arg.K8sVersion,
		)
		return err
	}
	_, err := q.db.Exec(ctx,
		`UPDATE clusters
		SET connection_status = $3::cluster_connection_status,
			connection_error = $4,
			updated_at = NOW()
		WHERE id = $1 AND org_id = $2`,
		arg.ID, arg.OrgID, arg.Status, arg.Error,
	)
	return err
}
