// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: team_access.sql

package repository

import "context"

// ─── tenant_team_access ────────────────────────────────────────────────

const tenantTeamAccessColumns = `id, org_id, cluster_id, tenant_name, team_id, granted_by, granted_at`

func scanTenantTeamAccess(row interface{ Scan(...interface{}) error }) (TenantTeamAccess, error) {
	var a TenantTeamAccess
	err := row.Scan(&a.ID, &a.OrgID, &a.ClusterID, &a.TenantName, &a.TeamID, &a.GrantedBy, &a.GrantedAt)
	return a, err
}

type GrantTenantTeamAccessParams struct {
	ID         string `json:"id"`
	OrgID      string `json:"org_id"`
	ClusterID  string `json:"cluster_id"`
	TenantName string `json:"tenant_name"`
	TeamID     string `json:"team_id"`
	GrantedBy  string `json:"granted_by"`
}

// GrantTenantTeamAccess records a team's access to a tenant. ON CONFLICT
// does nothing so repeated calls (e.g., a re-create after a delete) don't
// fail — the team already had access, so we're idempotent.
func (q *Queries) GrantTenantTeamAccess(ctx context.Context, arg GrantTenantTeamAccessParams) (TenantTeamAccess, error) {
	row := q.db.QueryRow(ctx,
		`INSERT INTO tenant_team_access (id, org_id, cluster_id, tenant_name, team_id, granted_by)
		VALUES ($1, $2, $3, $4, $5, $6)
		ON CONFLICT (cluster_id, tenant_name, team_id) DO UPDATE
		    SET granted_at = tenant_team_access.granted_at
		RETURNING `+tenantTeamAccessColumns,
		arg.ID, arg.OrgID, arg.ClusterID, arg.TenantName, arg.TeamID, arg.GrantedBy,
	)
	return scanTenantTeamAccess(row)
}

type RevokeTenantTeamAccessParams struct {
	OrgID      string `json:"org_id"`
	ClusterID  string `json:"cluster_id"`
	TenantName string `json:"tenant_name"`
	TeamID     string `json:"team_id"`
}

func (q *Queries) RevokeTenantTeamAccess(ctx context.Context, arg RevokeTenantTeamAccessParams) error {
	_, err := q.db.Exec(ctx,
		`DELETE FROM tenant_team_access
		WHERE org_id = $1 AND cluster_id = $2 AND tenant_name = $3 AND team_id = $4`,
		arg.OrgID, arg.ClusterID, arg.TenantName, arg.TeamID,
	)
	return err
}

// RevokeAllTenantTeamAccess clears access rows when a tenant is deleted
// via portal. Called by the handler's delete path so stale access rows
// don't linger after a tenant goes away.
type RevokeAllTenantTeamAccessParams struct {
	OrgID      string `json:"org_id"`
	ClusterID  string `json:"cluster_id"`
	TenantName string `json:"tenant_name"`
}

func (q *Queries) RevokeAllTenantTeamAccess(ctx context.Context, arg RevokeAllTenantTeamAccessParams) error {
	_, err := q.db.Exec(ctx,
		`DELETE FROM tenant_team_access
		WHERE org_id = $1 AND cluster_id = $2 AND tenant_name = $3`,
		arg.OrgID, arg.ClusterID, arg.TenantName,
	)
	return err
}

type ListTenantTeamAccessParams struct {
	OrgID      string `json:"org_id"`
	ClusterID  string `json:"cluster_id"`
	TenantName string `json:"tenant_name"`
}

func (q *Queries) ListTenantTeamAccess(ctx context.Context, arg ListTenantTeamAccessParams) ([]TenantTeamAccess, error) {
	rows, err := q.db.Query(ctx,
		`SELECT `+tenantTeamAccessColumns+` FROM tenant_team_access
		WHERE org_id = $1 AND cluster_id = $2 AND tenant_name = $3
		ORDER BY granted_at`,
		arg.OrgID, arg.ClusterID, arg.TenantName,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []TenantTeamAccess
	for rows.Next() {
		a, err := scanTenantTeamAccess(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, a)
	}
	if out == nil {
		out = []TenantTeamAccess{}
	}
	return out, rows.Err()
}

// ─── template_team_access ──────────────────────────────────────────────

const templateTeamAccessColumns = `id, org_id, template_id, team_id, granted_by, granted_at`

func scanTemplateTeamAccess(row interface{ Scan(...interface{}) error }) (TemplateTeamAccess, error) {
	var a TemplateTeamAccess
	err := row.Scan(&a.ID, &a.OrgID, &a.TemplateID, &a.TeamID, &a.GrantedBy, &a.GrantedAt)
	return a, err
}

type GrantTemplateTeamAccessParams struct {
	ID         string `json:"id"`
	OrgID      string `json:"org_id"`
	TemplateID string `json:"template_id"`
	TeamID     string `json:"team_id"`
	GrantedBy  string `json:"granted_by"`
}

func (q *Queries) GrantTemplateTeamAccess(ctx context.Context, arg GrantTemplateTeamAccessParams) (TemplateTeamAccess, error) {
	row := q.db.QueryRow(ctx,
		`INSERT INTO template_team_access (id, org_id, template_id, team_id, granted_by)
		VALUES ($1, $2, $3, $4, $5)
		ON CONFLICT (template_id, team_id) DO UPDATE
		    SET granted_at = template_team_access.granted_at
		RETURNING `+templateTeamAccessColumns,
		arg.ID, arg.OrgID, arg.TemplateID, arg.TeamID, arg.GrantedBy,
	)
	return scanTemplateTeamAccess(row)
}

type RevokeTemplateTeamAccessParams struct {
	OrgID      string `json:"org_id"`
	TemplateID string `json:"template_id"`
	TeamID     string `json:"team_id"`
}

func (q *Queries) RevokeTemplateTeamAccess(ctx context.Context, arg RevokeTemplateTeamAccessParams) error {
	_, err := q.db.Exec(ctx,
		`DELETE FROM template_team_access WHERE org_id = $1 AND template_id = $2 AND team_id = $3`,
		arg.OrgID, arg.TemplateID, arg.TeamID,
	)
	return err
}

type ListTemplateTeamAccessParams struct {
	OrgID      string `json:"org_id"`
	TemplateID string `json:"template_id"`
}

func (q *Queries) ListTemplateTeamAccess(ctx context.Context, arg ListTemplateTeamAccessParams) ([]TemplateTeamAccess, error) {
	rows, err := q.db.Query(ctx,
		`SELECT `+templateTeamAccessColumns+` FROM template_team_access
		WHERE org_id = $1 AND template_id = $2
		ORDER BY granted_at`,
		arg.OrgID, arg.TemplateID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []TemplateTeamAccess
	for rows.Next() {
		a, err := scanTemplateTeamAccess(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, a)
	}
	if out == nil {
		out = []TemplateTeamAccess{}
	}
	return out, rows.Err()
}

// ─── per-object access checks ─────────────────────────────────────────

// UserHasTenantAccess returns true when the user belongs to at least one
// team that has been granted access to the given (cluster, tenant) pair.
// Used by handlers that fetch a specific tenant — list filtering happens
// at query time, but Get/Delete/Operations need to gate single-object
// access too or a non-admin could read any tenant ID in the org.
// Admin-role bypass happens at the handler layer; this query trusts the
// caller has decided to scope by team.
func (q *Queries) UserHasTenantAccess(ctx context.Context, userID, orgID, clusterID, tenantName string) (bool, error) {
	row := q.db.QueryRow(ctx,
		`SELECT EXISTS(
			SELECT 1 FROM tenant_team_access tta
			JOIN team_members tm ON tm.team_id = tta.team_id
			WHERE tta.cluster_id = $1
			  AND tta.tenant_name = $2
			  AND tta.org_id = $3
			  AND tm.user_id = $4
		)`,
		clusterID, tenantName, orgID, userID,
	)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

// UserHasTemplateAccess is the template equivalent of UserHasTenantAccess.
func (q *Queries) UserHasTemplateAccess(ctx context.Context, userID, orgID, templateID string) (bool, error) {
	row := q.db.QueryRow(ctx,
		`SELECT EXISTS(
			SELECT 1 FROM template_team_access tta
			JOIN team_members tm ON tm.team_id = tta.team_id
			WHERE tta.template_id = $1
			  AND tta.org_id = $2
			  AND tm.user_id = $3
		)`,
		templateID, orgID, userID,
	)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

// ─── User → teams ──────────────────────────────────────────────────────

// ListUserTeamIDs returns the team IDs a user belongs to within an org.
// Used by the list endpoints to scope tenant + template results when the
// caller isn't an admin. Returns an empty slice when the user is in no
// teams — the caller decides whether that means "see nothing" (operator)
// or "see everything" (admin).
func (q *Queries) ListUserTeamIDs(ctx context.Context, userID, orgID string) ([]string, error) {
	rows, err := q.db.Query(ctx,
		`SELECT tm.team_id FROM team_members tm
		JOIN teams t ON t.id = tm.team_id
		WHERE tm.user_id = $1 AND t.org_id = $2`,
		userID, orgID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		out = append(out, id)
	}
	return out, rows.Err()
}
