// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tenants.sql

package repository

import (
	"context"
	"encoding/json"
	"time"
)

const tenantColumns = `id, org_id, cluster_id, name, phase, spec, status, last_observed_at, created_at, updated_at`

func scanTenant(row interface{ Scan(...interface{}) error }) (Tenant, error) {
	var t Tenant
	err := row.Scan(&t.ID, &t.OrgID, &t.ClusterID, &t.Name, &t.Phase, &t.Spec, &t.Status, &t.LastObservedAt, &t.CreatedAt, &t.UpdatedAt)
	return t, err
}

type GetTenantParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetTenant(ctx context.Context, arg GetTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx,
		`SELECT `+tenantColumns+` FROM tenants WHERE id = $1 AND org_id = $2`,
		arg.ID, arg.OrgID,
	)
	return scanTenant(row)
}

type ListTenantsParams struct {
	OrgID     string `json:"org_id"`
	ClusterID string `json:"cluster_id"`
	// TeamIDs scopes the result to tenants granted to one of these teams.
	// Nil = no team filter (caller is admin). Empty non-nil slice = explicit
	// "no teams to see" (non-admin in zero teams) — returns zero rows.
	TeamIDs []string `json:"team_ids"`
	Limit   int32    `json:"limit"`
	Offset  int32    `json:"offset"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	if arg.TeamIDs != nil {
		// Non-admin path: JOIN to access table, restrict to the user's teams.
		// Empty TeamIDs means the user is in no teams — short-circuit zero.
		if len(arg.TeamIDs) == 0 {
			return []Tenant{}, nil
		}
		rows, err := q.db.Query(ctx,
			`SELECT DISTINCT `+tenantColumnsPrefixed("t")+` FROM tenants t
			JOIN tenant_team_access tta
			  ON tta.cluster_id = t.cluster_id AND tta.tenant_name = t.name
			WHERE t.org_id = $1
			  AND ($2::TEXT = '' OR t.cluster_id = $2)
			  AND tta.team_id = ANY($3::TEXT[])
			ORDER BY t.cluster_id, t.name LIMIT $4 OFFSET $5`,
			arg.OrgID, arg.ClusterID, arg.TeamIDs, arg.Limit, arg.Offset,
		)
		return scanTenants(rows, err)
	}
	rows, err := q.db.Query(ctx,
		`SELECT `+tenantColumns+` FROM tenants
		WHERE org_id = $1
		  AND ($2::TEXT = '' OR cluster_id = $2)
		ORDER BY cluster_id, name LIMIT $3 OFFSET $4`,
		arg.OrgID, arg.ClusterID, arg.Limit, arg.Offset,
	)
	return scanTenants(rows, err)
}

// tenantColumnsPrefixed returns the column list with a table alias prefix,
// for JOIN queries that introduce ambiguous column references.
func tenantColumnsPrefixed(alias string) string {
	return alias + ".id, " + alias + ".org_id, " + alias + ".cluster_id, " + alias + ".name, " + alias + ".phase, " + alias + ".spec, " + alias + ".status, " + alias + ".last_observed_at, " + alias + ".created_at, " + alias + ".updated_at"
}

func scanTenants(rows interface {
	Next() bool
	Scan(...interface{}) error
	Err() error
	Close()
}, err error) ([]Tenant, error) {
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var tenants []Tenant
	for rows.Next() {
		t, err := scanTenant(rows)
		if err != nil {
			return nil, err
		}
		tenants = append(tenants, t)
	}
	if tenants == nil {
		tenants = []Tenant{}
	}
	return tenants, rows.Err()
}

type CountTenantsParams struct {
	OrgID     string   `json:"org_id"`
	ClusterID string   `json:"cluster_id"`
	TeamIDs   []string `json:"team_ids"`
}

func (q *Queries) CountTenants(ctx context.Context, arg CountTenantsParams) (int64, error) {
	if arg.TeamIDs != nil {
		if len(arg.TeamIDs) == 0 {
			return 0, nil
		}
		row := q.db.QueryRow(ctx,
			`SELECT COUNT(DISTINCT t.id) FROM tenants t
			JOIN tenant_team_access tta
			  ON tta.cluster_id = t.cluster_id AND tta.tenant_name = t.name
			WHERE t.org_id = $1
			  AND ($2::TEXT = '' OR t.cluster_id = $2)
			  AND tta.team_id = ANY($3::TEXT[])`,
			arg.OrgID, arg.ClusterID, arg.TeamIDs,
		)
		var count int64
		err := row.Scan(&count)
		return count, err
	}
	row := q.db.QueryRow(ctx,
		`SELECT COUNT(*) FROM tenants
		WHERE org_id = $1
		  AND ($2::TEXT = '' OR cluster_id = $2)`,
		arg.OrgID, arg.ClusterID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

// ListTenantNamesByCluster returns just the names known for a cluster.
// Used by the watcher to compute the deletion set: anything in the DB
// but not in the freshly-observed list is a tenant that's been removed
// from the cluster, and its row should be pruned.
func (q *Queries) ListTenantNamesByCluster(ctx context.Context, clusterID, orgID string) ([]string, error) {
	rows, err := q.db.Query(ctx,
		`SELECT name FROM tenants WHERE cluster_id = $1 AND org_id = $2`,
		clusterID, orgID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var names []string
	for rows.Next() {
		var n string
		if err := rows.Scan(&n); err != nil {
			return nil, err
		}
		names = append(names, n)
	}
	return names, rows.Err()
}

type UpsertTenantParams struct {
	ID             string          `json:"id"`
	OrgID          string          `json:"org_id"`
	ClusterID      string          `json:"cluster_id"`
	Name           string          `json:"name"`
	Phase          string          `json:"phase"`
	Spec           json.RawMessage `json:"spec"`
	Status         json.RawMessage `json:"status"`
	LastObservedAt time.Time       `json:"last_observed_at"`
}

// UpsertTenant inserts a new tenant row or, if (cluster_id, name) already
// exists, updates phase / spec / status / last_observed_at to the newly-
// observed values. ID is only used for INSERTs — UPDATEs preserve the
// existing row's ID so external references to it stay stable.
func (q *Queries) UpsertTenant(ctx context.Context, arg UpsertTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx,
		`INSERT INTO tenants (id, org_id, cluster_id, name, phase, spec, status, last_observed_at)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
		ON CONFLICT (cluster_id, name) DO UPDATE
		SET phase = EXCLUDED.phase,
		    spec = EXCLUDED.spec,
		    status = EXCLUDED.status,
		    last_observed_at = EXCLUDED.last_observed_at,
		    updated_at = NOW()
		RETURNING `+tenantColumns,
		arg.ID, arg.OrgID, arg.ClusterID, arg.Name, arg.Phase, arg.Spec, arg.Status, arg.LastObservedAt,
	)
	return scanTenant(row)
}

type DeleteTenantsByClusterAndNamesParams struct {
	ClusterID string   `json:"cluster_id"`
	OrgID     string   `json:"org_id"`
	Names     []string `json:"names"`
}

// DeleteTenantsByClusterAndNames hard-deletes tenant rows that the watcher
// no longer sees in a cluster. K8s is the source of truth — if the tenant
// is gone from the cluster, it shouldn't be in tofui either. Audit
// history lives in audit_logs.
func (q *Queries) DeleteTenantsByClusterAndNames(ctx context.Context, arg DeleteTenantsByClusterAndNamesParams) error {
	if len(arg.Names) == 0 {
		return nil
	}
	_, err := q.db.Exec(ctx,
		`DELETE FROM tenants WHERE cluster_id = $1 AND org_id = $2 AND name = ANY($3)`,
		arg.ClusterID, arg.OrgID, arg.Names,
	)
	return err
}
