#!/usr/bin/env bash
#
# seed.sh — bootstrap a fresh portal dev instance with:
#   1. Org-level AWS provider variables (env-category; non-sensitive)
#   2. Four landing-zone leaf workspaces (the eks-gitops prereqs):
#        lz-network → lz-cluster → lz-cluster-bootstrap → lz-cluster-addons
#      Each is an upload-source workspace whose archive is the full
#      landing-zone tree (terragrunt needs parent files for
#      find_in_parent_folders); working_dir points at the leaf.
#   3. A pipeline `eks-gitops-prereqs` chaining the four stages.
#
# Idempotent: skips workspaces/vars/pipelines that already exist by name.
#
# Requires: curl, jq, tar; portal server reachable; ENVIRONMENT=development
# so the /auth/dev login endpoint is enabled.
#
# Configure via env vars (defaults match a typical local setup):
#   PORTAL_API           default http://localhost:8080
#   LANDING_ZONE_PATH   default $HOME/codes/nanohype/landing-zone
#   LZ_ACCOUNT          default workload-production
#   LZ_REGION           default us-west-2
#   LZ_ENV              default production
#   AWS_PROFILE_NAME    default default — the AWS shared-config profile the
#                       seeded workspaces run under
#   TOFU_VERSION        default 1.11.0
#   REUPLOAD            default false — when true, existing workspaces get
#                       the freshly-packed archive uploaded over them
#                       instead of being skipped. Org vars + pipeline are
#                       still treated as idempotent (skipped when present).

set -euo pipefail

API=${PORTAL_API:-http://localhost:8080}
LZ_PATH=${LANDING_ZONE_PATH:-$HOME/codes/nanohype/landing-zone}
ACCOUNT=${LZ_ACCOUNT:-workload-production}
REGION=${LZ_REGION:-us-west-2}
ENV=${LZ_ENV:-production}
PROFILE=${AWS_PROFILE_NAME:-default}
TOFU_VERSION=${TOFU_VERSION:-1.11.0}
REUPLOAD=${REUPLOAD:-false}

for bin in curl jq tar; do
  command -v "$bin" >/dev/null || { echo "missing: $bin" >&2; exit 1; }
done

if [ ! -d "$LZ_PATH/live/aws/$ACCOUNT/$REGION/$ENV" ]; then
  echo "landing-zone path not found: $LZ_PATH/live/aws/$ACCOUNT/$REGION/$ENV" >&2
  exit 1
fi

echo "==> Authenticating against $API"
# Log in the way the SPA does. /auth/dev mints the JWT and hands it back as an
# HttpOnly cookie scoped to /auth/handoff, then redirects to the callback page —
# the token is never in the URL. One POST to /auth/handoff exchanges that cookie
# for the token as JSON and expires it, so this runs exactly once.
COOKIES=$(mktemp -t portal-seed-cookies.XXXXXX)
trap 'rm -f "$COOKIES"' EXIT
if ! curl -fsS -o /dev/null -c "$COOKIES" "$API/api/v1/auth/dev"; then
  echo "    /auth/dev did not respond — is the server up with ENVIRONMENT=development?" >&2
  exit 1
fi
TOKEN=$(curl -fsS -b "$COOKIES" -X POST "$API/api/v1/auth/handoff" | jq -r '.token // empty')
if [ -z "$TOKEN" ]; then
  echo "    failed to obtain token from /auth/dev — is ENVIRONMENT=development?" >&2
  exit 1
fi
ME=$(curl -fsS -H "Authorization: Bearer $TOKEN" "$API/api/v1/auth/me")
ORG_ID=$(jq -r .org_id <<<"$ME")
echo "    org_id=$ORG_ID  user=$(jq -r .email <<<"$ME")"

auth() { curl -fsS -H "Authorization: Bearer $TOKEN" "$@"; }
auth_json() { auth -H "Content-Type: application/json" "$@"; }

# ─── 1. Org variables ──────────────────────────────────────────────
echo
echo "==> Seeding org-level AWS variables"
# Every list endpoint answers with the {data,total,page,per_page} envelope.
existing_vars=$(auth "$API/api/v1/variables" | jq -r '.data[]?.key')

seed_var() {
  local key=$1 value=$2 sensitive=$3 category=$4 desc=$5
  if grep -qx "$key" <<<"$existing_vars"; then
    echo "    skip  $key  (already set)"
    return
  fi
  auth_json -X POST "$API/api/v1/variables" -d "$(
    jq -nc --arg k "$key" --arg v "$value" --argjson s "$sensitive" --arg c "$category" --arg d "$desc" \
      '{key:$k, value:$v, sensitive:$s, category:$c, description:$d}'
  )" >/dev/null
  echo "    ✓     $key  ($category)"
}

seed_var AWS_PROFILE        "$PROFILE" false env "AWS profile used by all workspaces"
seed_var AWS_REGION         "$REGION"  false env "Region for AWS provider"
seed_var AWS_DEFAULT_REGION "$REGION"  false env "Region fallback for AWS provider"

# ─── 2. Workspaces (landing-zone leaves) ───────────────────────────
echo
echo "==> Packing landing-zone tree from $LZ_PATH"
ARCHIVE=$(mktemp -t portal-lz.XXXXXX).tar.gz
# One EXIT trap for the whole script — a second `trap ... EXIT` would replace
# the login one and leave the cookie jar behind.
trap 'rm -f "$ARCHIVE" "$COOKIES"' EXIT
# Exclude regenerable / oversized junk:
#   .terraform           — provider plugins; re-downloaded by `tofu init`
#   .terragrunt-cache    — rendered output; regenerated by `terragrunt init`
#   .git                 — not needed at runtime
#   *.tfstate*           — local state files (we use remote backends)
#   *.tfplan             — plan binaries
# The worker has a 50 MB upload cap; the source-only tree typically lands
# under a few MB.
tar czf "$ARCHIVE" -C "$LZ_PATH" \
  --exclude='./.terraform' --exclude='*/.terraform' \
  --exclude='./.terragrunt-cache' --exclude='*/.terragrunt-cache' \
  --exclude='./.git' \
  --exclude='*.tfstate' --exclude='*.tfstate.backup' --exclude='*.tfplan' \
  .
SIZE_BYTES=$(stat -f%z "$ARCHIVE" 2>/dev/null || stat -c%s "$ARCHIVE")
SIZE_MB=$(( SIZE_BYTES / 1024 / 1024 ))
echo "    ${SIZE_MB}M  $ARCHIVE"
if [ "$SIZE_BYTES" -gt $((50 * 1024 * 1024)) ]; then
  echo "    ERROR: archive exceeds the 50 MB upload limit. Check for stray" >&2
  echo "    artifacts not covered by the exclude list." >&2
  exit 1
fi

STAGES=(network cluster cluster-bootstrap cluster-addons)
declare -A WORKSPACE_IDS

echo
echo "==> Creating prereq workspaces"
workspaces_json=$(auth "$API/api/v1/workspaces?per_page=100")
for stage in "${STAGES[@]}"; do
  name="lz-${stage}"
  working_dir="live/aws/${ACCOUNT}/${REGION}/${ENV}/${stage}"

  # check leaf exists locally so we fail before hitting the API
  if [ ! -f "$LZ_PATH/$working_dir/terragrunt.hcl" ]; then
    echo "    SKIP  $name — $working_dir/terragrunt.hcl not found locally"
    continue
  fi

  existing_id=$(jq -r --arg n "$name" '.data[] | select(.name==$n) | .id' <<<"$workspaces_json" | head -1)
  if [ -n "$existing_id" ]; then
    WORKSPACE_IDS[$stage]=$existing_id
    if [ "$REUPLOAD" = "true" ]; then
      auth -X POST "$API/api/v1/workspaces/$existing_id/upload" -F "file=@$ARCHIVE" >/dev/null
      echo "    ↑     $name  (id=$existing_id, re-uploaded)"
    else
      echo "    skip  $name  (id=$existing_id)"
    fi
    continue
  fi

  ws_id=$(auth_json -X POST "$API/api/v1/workspaces" -d "$(
    jq -nc --arg n "$name" --arg wd "$working_dir" --arg env "$ENV" --arg tv "$TOFU_VERSION" \
      '{name:$n, source:"upload", working_dir:$wd, environment:$env, tofu_version:$tv, auto_apply:false, requires_approval:false}'
  )" | jq -r .id)

  auth -X POST "$API/api/v1/workspaces/$ws_id/upload" -F "file=@$ARCHIVE" >/dev/null

  # Seed the terraform-category vars every landing-zone leaf needs. These
  # are declared in each component's variables.tf with no defaults, so
  # plan fails fast without them. Terragrunt's `inputs = {}` block doesn't
  # set them either (they're cross-cutting). TF_VAR_ injection (lowest
  # precedence) means terragrunt can still override if it ever wants to.
  for kv in "environment=$ENV" "region=$REGION" "tags={}"; do
    k=${kv%%=*}; v=${kv#*=}
    auth_json -X POST "$API/api/v1/workspaces/$ws_id/variables" \
      -d "$(jq -nc --arg k "$k" --arg v "$v" '{key:$k, value:$v, sensitive:false, category:"terraform"}')" >/dev/null
  done
  echo "    ✓     $name  (id=$ws_id, working_dir=$working_dir)"
  WORKSPACE_IDS[$stage]=$ws_id
done

# ─── 3. Pipeline ───────────────────────────────────────────────────
echo
echo "==> Creating pipeline eks-gitops-prereqs"
pipeline_name=eks-gitops-prereqs

# Build the stages array from STAGES + WORKSPACE_IDS. Skip if any workspace
# is missing (the local leaf wasn't found).
stages_json='[]'
for stage in "${STAGES[@]}"; do
  ws_id=${WORKSPACE_IDS[$stage]:-}
  [ -z "$ws_id" ] && { echo "    skipped stage $stage (no workspace)"; continue; }
  stages_json=$(jq --arg id "$ws_id" '. + [{workspace_id:$id, auto_apply:false, on_failure:"stop"}]' <<<"$stages_json")
done

if [ "$(jq length <<<"$stages_json")" -eq 0 ]; then
  echo "    no stages to chain — skipping pipeline"
  exit 0
fi

existing_pipeline=$(auth "$API/api/v1/pipelines" | jq -r --arg n "$pipeline_name" '.data[]? | select(.name==$n) | .id' | head -1)
if [ -n "$existing_pipeline" ]; then
  echo "    skip  $pipeline_name  (id=$existing_pipeline)"
else
  pipeline_id=$(auth_json -X POST "$API/api/v1/pipelines" -d "$(
    jq -nc --arg n "$pipeline_name" --arg d "Landing-zone prereqs for eks-gitops: network → cluster → bootstrap → addons" --argjson s "$stages_json" \
      '{name:$n, description:$d, stages:$s}'
  )" | jq -r .id)
  echo "    ✓     $pipeline_name  (id=$pipeline_id, stages=$(jq length <<<"$stages_json"))"
fi

echo
echo "Done. Open http://localhost:5173 to plan / apply."
