import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import path from 'path';

export default defineConfig({
  plugins: [react(), tailwindcss()],
  build: {
    outDir: 'dist',
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  test: {
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov'],
      reportsDirectory: './coverage',
      // Explicit include so a module with zero tests still counts against the
      // floor. Without it v8 only measures files the suite happened to import,
      // which makes the gate vacuous — adding an untested file would raise the
      // percentage rather than lower it.
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/**/*.test.{ts,tsx}',
        'src/test/**', // suite setup
        'src/api/types.ts', // generated from api/openapi.yaml; CI gates its drift
        'src/routeTree.gen.ts', // generated by the router plugin
        'src/**/*.d.ts',
      ],
      thresholds: {
        // A ratchet, not the org floor. The org number is branches 60 /
        // functions 75 / lines 75 / statements 75 (nanohype/standards/
        // testing-rubric.json); portal's web surface measures well below it
        // because the React component tree is largely untested while the logic
        // under src/lib is not. Claiming 75 here would fail every build without
        // making anything safer, so the global numbers sit just under measured
        // and ratchet upward, and the layers that can hold the org floor are
        // held to it below.
        statements: 28, // measured 29.17
        branches: 29, // measured 30.45
        functions: 22, // measured 23.95
        lines: 29, // measured 30.47

        // src/lib is the logic layer — role checks, status derivation, CIDR and
        // fleet maths. It carries the org floor.
        'src/lib/**': {
          statements: 75,
          branches: 60,
          functions: 75,
          lines: 75,
        },

        // roles.ts decides what a user is allowed to do in the UI. It mirrors
        // internal/auth/rbac.go, which the Go gate pins at 100 for the same
        // reason: a wrong branch here shows an action the API will refuse, or
        // hides one it would have allowed.
        'src/lib/roles.ts': {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
      },
    },
  },
  server: {
    port: 5173,
    proxy: {
      '/api': {
        target: 'http://localhost:8080',
        changeOrigin: true,
        ws: true,
      },
    },
  },
});
